export enum Type {
  ELEVATED = 'ELEVATED',
  DECREASED = 'DECREASED',
  NORMAL = 'NORMAL',
  NOTZERO = 'NOTZERO',
  NOTELEVATED = 'NOTELEVATED',
  NOTDECREASED= 'NOTDECREASED',
  POSITIVE = 'POSITIVE',
  NEGATIVE = 'NEGATIVE',
}
